config/routes.rb
Slapp::Application.routes.draw do

  namespace :api, :defaults => {:format => :json}  do
    namespace :v1 do
      resources :orders
    end
  end

  get '/users/:id/set', to: 'users#set_is_sharer', as: 'set_is_sharer'
  get '/users/:id/unset', to: 'users#unset_is_sharer', as: 'unset_is_sharer'
  get '/shares/choose', to: 'shares#choose', as: 'sharer_choose'
  get '/shares/list', to: 'shares#list', as: 'monthly_list'
  match '/shares/:id/grade', to: 'shares#grade', as: 'share_grade'

  resources :shares

  resources :restaurants

  resources :recharges

  resources :accounts

  match '/dish_order/:id', to: 'orders#dish_order', as: 'dish_order'
  get '/orders/list', to: 'orders#list', as: 'list_today'

  resources :orders

  get '/dishes/:id/set', to: 'dishes#set_is_today', as: 'set_is_today'
  get '/dishes/:id/unset', to: 'dishes#unset_is_today', as: 'unset_is_today'

  resources :dishes

  root :to => 'index#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :posts do
    resources :comments
  end

  devise_for :users
  ActiveAdmin.routes(self)

end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to :user

  attr_accessible :amount, :remark
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :restaurant
  attr_accessible :restaurant_id, :description, :name, :price, :remark, :is_today, :set_date
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :dish_name, :dish_price, :order_date, :remark

  belongs_to :user
  belongs_to :restaurant

  validates :user_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title, :tags_attributes

  validates :title , :presence => true
  validates :content, :presence => true

  has_many :comments, :dependent => :destroy
  has_many :tags

  accepts_nested_attributes_for :tags, :allow_destroy => :true,
  	:reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

app/models/recharge.rb
class Recharge < ActiveRecord::Base

  belongs_to :user

  attr_accessible :operator, :recharge_amount, :recharge_date, :remark
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :dishes, dependent: :destroy
  has_many :orders, dependent: :destroy
  attr_accessible :address, :name, :phone, :remark
end

app/models/share.rb
class Share < ActiveRecord::Base
  attr_accessible :remark, :sharing_content, :sharing_date, :sum_graded, :total_grade, :user_id, :is_archived

  belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :account , dependent: :destroy
  has_many :orders , dependent: :destroy
  has_many :recharges , dependent: :destroy
  has_many :shares, dependent: :destroy

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :username, :password, :password_confirmation, :remember_me, :is_sharer
  # attr_accessible :title, :body
  validates :username, :uniqueness => { :case_sensitive => false }

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    date = Time.now
    date_today = date.strftime("%Y-%m-%d")
    @dishes_today = Dish.find_all_by_is_today_and_set_date(true, date_today)

    @last_post = Post.last

    if current_user.account.nil?
      user_account = Account.new(:amount => 0)
      current_user.account = user_account
    end
  end
end

app/controllers/shares_controller.rb
class SharesController < InheritedResources::Base
  before_filter :authenticate_user!
  before_filter :authorize_admin!, :only => [:delete, :update, :list, :choose]
  before_filter :active_sharers

  def choose
    @users = User.all

    respond_to do |format|
      format.html # choose.html.erb
      format.json { render json: @users }
    end
  end

  def index
    date = Time.now

    if params[:share_date].nil?
      date_today = date.strftime("%Y-%m-%d")
    else
      date_today = Date.civil(params[:share_date][:year].to_i, params[:share_date][:month].to_i, params[:share_date][:day].to_i)
    end

    @shares = Share.find_all_by_sharing_date(date_today, :order => 'sharing_date DESC')


    #@total = 0
    #@orders.each do |order|
    #  @total += order.dish_price
    #end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shares }
    end
  end

  def list
    date = Time.now

    if ((params[:shares_year].nil?) || (params[:shares_month].nil?))
      shares_year = date.year
      shares_month = date.month
    else
      shares_year = params[:shares_year][:year].to_i
      shares_month = params[:shares_month][:month].to_i
    end

    shares_date = Date.civil(shares_year, shares_month, 1)
    shares_date_month = shares_date.end_of_month

    @shares = Share.where(:sharing_date => shares_date..shares_date_month).order('sharing_date DESC')

    respond_to do |format|
      format.html # list.html.erb
      format.json { render json: @shares }
    end

  end

  def grade
    @share = Share.find(params[:id])

    name_list = @share.remark
    sum_graded = @share.sum_graded
    total_grade = @share.total_grade

    if name_list.nil?
      name_list = ''
    end

    if sum_graded.nil?
      sum_graded = 0
    end

    if total_grade.nil?
      total_grade = 0
    end

    if @share.is_archived
      respond_to do |format|
        format.html { redirect_to shares_path, alert: t('global.share.error.archived') }
        format.json { head :no_content }
      end
    else
      if name_list.include?(current_user.username)
        respond_to do |format|
          format.html { redirect_to shares_path, alert: t('global.share.error.voted') }
          format.json { head :no_content }
        end
      else
        tsum = sum_graded * total_grade + params[:grade_point].to_i
        pnum = total_grade + 1
        tsum = tsum / pnum

        @share.sum_graded = tsum
        @share.total_grade = pnum
        @share.remark = name_list + "." + current_user.username

        @share.save
        respond_to do |format|
          format.html { redirect_to shares_path, notice: t('global.share.info.voted1') + @share.user.username + t('global.share.info.voted2') }
          format.json { head :no_content }
        end
      end
    end
  end

  def active_sharers
    @active_sharers = User.find_all_by_is_sharer(true)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admins_only(&block)
    block.call if current_user.try(:admin?)
    nil
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def join_tags(post)
		post.tags.map { |t| t.name }.join(" | ")
	end
end

app/helpers/recharges_helper.rb
module RechargesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shares/_form.html.erb
<%= form_for(@share) do |f| %>
  <% if @share.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@share.errors.count, "error") %> prohibited this share from being saved:</h2>

      <ul>
      <% @share.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.select :user_id, options_from_collection_for_select(@active_sharers, "id", "username", @share.user_id), :prompt => "选择分享人员" %>
  </div>
  <div class="field">
    <%= f.label :sharing_date %><br />
    <%= f.date_select :sharing_date %>
  </div>
  <div class="field">
    <%= f.label :sharing_content %><br />
    <%= f.text_field :sharing_content %>
  </div>
  <div class="field">
    <%= f.label :sum_graded %><br />
    <%= f.text_field :sum_graded %>
  </div>
  <div class="field">
    <%= f.label :total_grade %><br />
    <%= f.text_field :total_grade %>
  </div>
  <div class="field">
      <%= f.check_box :is_archived %><%= f.label :is_archived %>
    </div>
  <div class="actions">
    <%= f.submit  :class => 'btn btn-xs btn-success' %>
  </div>
<% end %>

app/views/shares/choose.html.erb
<div class="panel panel-success">
  <div class="panel-heading">晨会分享人员</div>

  <table class="table table-striped">
    <tr>
      <th>人员</th>
      <th>是否主持晨会</th>
    </tr>

    <% @users.each do |user| %>
        <tr>
          <td><%= user.username %></td>

          <td>
            <% if  user.is_sharer %>
                <%= link_to '取消', unset_is_sharer_path(user), :class => 'btn btn-xs btn-danger' %>
            <% else %>
                <%= link_to '选定', set_is_sharer_path(user), :class => 'btn btn-xs btn-success' %>
            <% end %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/shares/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-success">

      <div class="panel-heading">修改晨会分享</div>
      <div class="panel-body">

        <%= render 'form' %>

        <%= link_to '返回', shares_path, :class => 'btn btn-xs btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/shares/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-success">

      <div class="panel-heading">晨会分享</div>
      <div class="panel-body">

        <form class="form-search">
          <%= select_date Date.today, prefix: :share_date %>
          <button type="submit" class="btn btn-xs btn-primary">查看</button>
          <%= admins_only do %>
              <%= link_to '设定分享', new_share_path, :class => 'btn btn-xs btn-success' %>
          <% end %>
        </form>

      </div>

      <table class="table table-striped">
        <tr>
          <th>日期</th>
          <th>人员</th>
          <th>分享内容</th>
          <th></th>
          <%= admins_only do %>
              <th>评分</th>
              <th>评分人数</th>
              <th>已存档</th>
              <th>操作</th>
          <% end %>
        </tr>

        <% @shares.each do |share| %>
            <tr>
              <td><%= share.sharing_date %></td>
              <td><%= share.user.username %></td>
              <td><%= share.sharing_content %></td>
              <td><!-- Button trigger modal -->
                <button class="btn btn-xs btn-success" data-toggle="modal" data-target="#myModal">
                  评分
                </button>
              </td>
              <%= admins_only do %>
                  <td><%= share.sum_graded %></td>
                  <td><%= share.total_grade %></td>
                  <td>
                    <% if share.is_archived %>
                        是
                    <% else %>
                        否
                    <% end %>
                  </td>
                  <td><%= link_to '修改', edit_share_path(share), :class => 'btn btn-xs btn-info' %>
                    <%= link_to '删除', share, method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-xs btn-danger' %>
                  </td>
              <% end %>
            </tr>

            <!-- Modal -->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">给<%= share.user.username %>评分</h4>
                  </div>
                  <div class="modal-body" style="text-align: center;">

                    <%= form_for('grade-form', :url => share_grade_path(share)) do |f| %>
                        <div class="form-group">
                        <%= select_tag(:grade_point, options_for_select((0..100).map { |c| [c, c] }, :selected => 100), {:class => 'form-control', :size => '10'}) %>
                        </div>
                        <div class="form-group">
                          <%= f.submit '提交', :class => 'btn btn-success' %>
                          <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        </div>

                    <% end %>
                  </div>
                </div>
                <!-- /.modal-content -->
              </div>
              <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->

        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/shares/list.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-success">

      <div class="panel-heading">月度晨会评分</div>
      <div class="panel-body">

        <form class="form-search">
          <%= select_year Date.today, prefix: :shares_year %>
          <%= select_month Date.today, prefix: :shares_month %>
          <button type="submit" class="btn btn-primary">查看</button>
        </form>
      </div>

      <table class="table table-striped">
        <tr>
          <th>日期</th>
          <th>人员</th>
          <th>分享内容</th>
          <%= admins_only do %>
              <th>评分</th>
              <th>评分人数</th>
              <th>已存档</th>
          <% end %>
        </tr>

        <% @shares.each do |share| %>
            <tr>
              <td><%= share.sharing_date %></td>
              <td><%= share.user.username %></td>
              <td><%= share.sharing_content %></td>
              <%= admins_only do %>
                  <td><%= share.sum_graded %></td>
                  <td><%= share.total_grade %></td>
                  <td>
                    <% if share.is_archived %>
                        是
                    <% else %>
                        否
                    <% end %>
                  </td>
              <% end %>
            </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/shares/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-success">

      <div class="panel-heading">设定晨会分享</div>
      <div class="panel-body">

        <%= render 'form' %>

        <%= link_to '返回', shares_path, :class => 'btn btn-xs btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/shares/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-success">

      <div class="panel-heading">设定晨会分享</div>
      <div class="panel-body">
        <p>
          <b>用户:</b>
          <%= @share.user.username %>
        </p>

        <p>
          <b>分享日期:</b>
          <%= @share.sharing_date %>
        </p>

        <p>
          <b>分享内容:</b>
          <%= @share.sharing_content %>
        </p>

        <p>
          <b>平均得分:</b>
          <%= @share.sum_graded %>
        </p>

        <p>
          <b>评分人数:</b>
          <%= @share.total_grade %>
        </p>

        <p>
          <b>是否已存档:</b>
          <%= @share.is_archived %>
        </p>


        <%= link_to '返回', shares_path, :class => 'btn btn-xs btn-primary' %>
      </div>
    </div>
  </div>
</div>