config/routes.rb
Slapp::Application.routes.draw do

  namespace :api, :defaults => {:format => :json}  do
    namespace :v1 do
      resources :orders
    end
  end

  get '/users/:id/set', to: 'users#set_is_sharer', as: 'set_is_sharer'
  get '/users/:id/unset', to: 'users#unset_is_sharer', as: 'unset_is_sharer'
  get '/shares/choose', to: 'shares#choose', as: 'sharer_choose'
  get '/shares/list', to: 'shares#list', as: 'monthly_list'
  match '/shares/:id/grade', to: 'shares#grade', as: 'share_grade'

  resources :shares

  resources :restaurants

  resources :recharges

  resources :accounts

  match '/dish_order/:id', to: 'orders#dish_order', as: 'dish_order'
  get '/orders/list', to: 'orders#list', as: 'list_today'

  resources :orders

  get '/dishes/:id/set', to: 'dishes#set_is_today', as: 'set_is_today'
  get '/dishes/:id/unset', to: 'dishes#unset_is_today', as: 'unset_is_today'

  resources :dishes

  root :to => 'index#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :posts do
    resources :comments
  end

  devise_for :users
  ActiveAdmin.routes(self)

end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to :user

  attr_accessible :amount, :remark
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :restaurant
  attr_accessible :restaurant_id, :description, :name, :price, :remark, :is_today, :set_date
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :dish_name, :dish_price, :order_date, :remark

  belongs_to :user
  belongs_to :restaurant

  validates :user_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title, :tags_attributes

  validates :title , :presence => true
  validates :content, :presence => true

  has_many :comments, :dependent => :destroy
  has_many :tags

  accepts_nested_attributes_for :tags, :allow_destroy => :true,
  	:reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

app/models/recharge.rb
class Recharge < ActiveRecord::Base

  belongs_to :user

  attr_accessible :operator, :recharge_amount, :recharge_date, :remark
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :dishes, dependent: :destroy
  has_many :orders, dependent: :destroy
  attr_accessible :address, :name, :phone, :remark
end

app/models/share.rb
class Share < ActiveRecord::Base
  attr_accessible :remark, :sharing_content, :sharing_date, :sum_graded, :total_grade, :user_id, :is_archived

  belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :account , dependent: :destroy
  has_many :orders , dependent: :destroy
  has_many :recharges , dependent: :destroy
  has_many :shares, dependent: :destroy

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :username, :password, :password_confirmation, :remember_me, :is_sharer
  # attr_accessible :title, :body
  validates :username, :uniqueness => { :case_sensitive => false }

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admins_only(&block)
    block.call if current_user.try(:admin?)
    nil
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def join_tags(post)
		post.tags.map { |t| t.name }.join(" | ")
	end
end

app/helpers/recharges_helper.rb
module RechargesHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index/index.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="box box-success">
      <div class="box-header">
        <h3 class="box-title"><i class="fa fa-user-plus"></i> 准备就餐</h3>
      </div>
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover" ng-controller="OrdersCtrl">
          <tr>
            <th style="text-align: center">人员</th>
            <th style="text-align: center">菜名</th>
            <%= admins_only do %>
                <th>操作</th>
            <% end %>
          </tr>
          <tr ng-repeat="order in orders">
            <td style="text-align: center">{{order.remark}}</td>
            <td style="text-align: center">{{order.dish_name}}</td>
            <%= admins_only do %>
                <td>
                  <a href='' class="btn btn-xs btn-danger" ng-click="deleteOrder(order.id, $index)">删除</a>
                </td>
            <% end %>
          </tr>
        </table>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="box box-success">
      <div class="box-header">
        <h3 class="box-title"><i class="fa fa-plus-square"></i> 今日菜单</h3>
      </div>
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <tr>
            <th>菜名</th>
            <th>价格</th>
            <th>日期</th>
            <th>操作</th>
          </tr>

          <% @dishes_today.each do |dish| %>
              <tr>
                <td><%= dish.name %></td>
                <td><%= dish.price %></td>
                <td><%= dish.set_date %></td>
                <td><%= link_to '选择', dish_order_path(dish), :class => 'btn btn-xs btn-success submit_order', :id => 'submit_order' %>
                </td>
              </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">正在提交ing</h4>
      </div>
      <div class="modal-body">
        亲，请耐心等待，您的订餐正在提交中~~~
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
<script>
    $("i.fa.fa-home").closest("li").addClass("active");
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app='SmartLunch'>
<head>
  <title><%= t('global.application.name') %></title>
  <link href="<%= image_path("favicon.ico") %>" rel="shortcut icon" type="image/vnd.microsoft.icon" />
  <!--[if lt IE 9]>
  <script src="/assets/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<% if user_signed_in? %>

<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <div class="logo">
      <span class="logo-mini"><img src="/assets/logo.png" style="height:30px;"/></span>
      <span class="logo-lg"><img src="/assets/logo.png" style="height:40px;"/> <b>Smart</b>Lunch</span>
    </div>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->

          <% if user_signed_in? %>
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-gears"></i><b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to  edit_registration_path(:user) do %>
                        <span><i class="fa fa-tasks"></i> <%= t('global.menu.changepassword') %></span>
                    <% end %>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to  list_today_path do %>
                        <span><i class="fa fa-tasks"></i> 查看今日订餐</span>
                    <% end %>
                  </li>
                  <%= admins_only do %>
                      <li><%= link_to '设置今日菜单', dishes_path %></li>
                      <li><%= link_to '账户管理', accounts_path %></li>
                      <li><%= link_to '充值记录', recharges_path %></li>
                      <li><%= link_to '餐馆列表', restaurants_path %></li>
                      <!--                         <li class = "divider"></li>
                                              <li>< = link _to '设置晨会主持', sharer _choose _path ></li>
                                              <li>< = link _to '查看晨会评分', monthly _list _path ></li> -->
                  <% end %>
                  <li class="divider"></li>
                  <li>
                    <%= link_to destroy_user_session_path, :method => :delete do %>
                        <span><i class="fa fa-sign-out"></i> <%= t('global.menu.signout') %></span>
                    <% end %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li>
                <%= link_to t('global.menu.signin'), new_user_session_path %></li>
              <li>
                <%= link_to t('global.menu.signup'), new_user_registration_path %></li>
          <% end %>


        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="/assets/adminlte/user-160x160.png" class="img-circle" />
        </div>
        <div class="pull-left info">
          <p><%= current_user.username %></p>
          <!-- Status -->
          <p>
            <% if current_user.account.amount > 0 %>
                <span><i class="fa fa-circle text-success"></i>
                账户余额：<%= current_user.account.amount %></span>
            <% else %>
                <span><i class="fa fa-circle text-danger"></i>
                  账户余额：<%= current_user.account.amount %></span>
            <% end %>
          </p>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        <li class="treeview">
          <%= link_to root_path do %>
            <i class="fa fa-home"></i>
            <span><%= t('global.menu.home') %></span>
          <% end %>
        </li>
        <li class="treeview">
          <%= link_to posts_path do %>
          <i class="fa fa-list"></i>
          <span><%= t('global.menu.blog') %></span>
            <% end %>
        </li>
        <li class="treeview">
          <%= link_to orders_path do %>
          <i class="fa fa-book"></i>
          <span><%=  t('global.menu.lunch') %></span>
          <% end %>
        </li>
      </ul><!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <% flash.each do |key, value| %>
              <div class='callout callout-info' id='<%= key %>'>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <span class="glyphicon glyphicon-check"></span><%= value %>
              </div>
          <% end %>
        </div>
      </div>
    </section>

    <!-- Main content -->
    <section class="content">

      <%= yield %>


    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      <p>智慧生活 用<span style="color: red;" class="glyphicon glyphicon-heart"></span>创造</p>
    </div>
    <!-- Default to the left -->
    <p>智慧点餐系统 v3.2.0 &copy; 2015 <a target="_blank" href="http://wrisc.cn">WRISC</a></p>
  </footer>

</div><!-- ./wrapper -->

    <script>
        $(document.body).addClass("skin-black-light sidebar-mini");
    </script>

<% else %>
    <%= yield %>
<% end %>

</body>
</html>