config/routes.rb
Slapp::Application.routes.draw do

  namespace :api, :defaults => {:format => :json}  do
    namespace :v1 do
      resources :orders
    end
  end

  get '/users/:id/set', to: 'users#set_is_sharer', as: 'set_is_sharer'
  get '/users/:id/unset', to: 'users#unset_is_sharer', as: 'unset_is_sharer'
  get '/shares/choose', to: 'shares#choose', as: 'sharer_choose'
  get '/shares/list', to: 'shares#list', as: 'monthly_list'
  match '/shares/:id/grade', to: 'shares#grade', as: 'share_grade'

  resources :shares

  resources :restaurants

  resources :recharges

  resources :accounts

  match '/dish_order/:id', to: 'orders#dish_order', as: 'dish_order'
  get '/orders/list', to: 'orders#list', as: 'list_today'

  resources :orders

  get '/dishes/:id/set', to: 'dishes#set_is_today', as: 'set_is_today'
  get '/dishes/:id/unset', to: 'dishes#unset_is_today', as: 'unset_is_today'

  resources :dishes

  root :to => 'index#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :posts do
    resources :comments
  end

  devise_for :users
  ActiveAdmin.routes(self)

end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to :user

  attr_accessible :amount, :remark
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :restaurant
  attr_accessible :restaurant_id, :description, :name, :price, :remark, :is_today, :set_date
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :dish_name, :dish_price, :order_date, :remark

  belongs_to :user
  belongs_to :restaurant

  validates :user_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title, :tags_attributes

  validates :title , :presence => true
  validates :content, :presence => true

  has_many :comments, :dependent => :destroy
  has_many :tags

  accepts_nested_attributes_for :tags, :allow_destroy => :true,
  	:reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

app/models/recharge.rb
class Recharge < ActiveRecord::Base

  belongs_to :user

  attr_accessible :operator, :recharge_amount, :recharge_date, :remark
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :dishes, dependent: :destroy
  has_many :orders, dependent: :destroy
  attr_accessible :address, :name, :phone, :remark
end

app/models/share.rb
class Share < ActiveRecord::Base
  attr_accessible :remark, :sharing_content, :sharing_date, :sum_graded, :total_grade, :user_id, :is_archived

  belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :account , dependent: :destroy
  has_many :orders , dependent: :destroy
  has_many :recharges , dependent: :destroy
  has_many :shares, dependent: :destroy

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :username, :password, :password_confirmation, :remember_me, :is_sharer
  # attr_accessible :title, :body
  validates :username, :uniqueness => { :case_sensitive => false }

end

app/controllers/api/v1/dishes_controller.rb
class API::V1::DishesController < ApplicationController
	before_filter :authenticate_user!
  	before_filter :authorize_admin!, :only => [:delete, :update]

	def index
		date = Time.now
	    date_today = date.strftime("%Y-%m-%d")
	    @dishes = Dish.find_all_by_is_today_and_set_date(true, date_today)

	   	respond_to do |format|
	      format.json { render json: @dishes }
	    end
	end
end

app/controllers/dishes_controller.rb
class DishesController < InheritedResources::Base
  before_filter :authorize_admin!, :except => [:index, :show]

  def set_is_today
    @dish = Dish.find(params[:id])

    t = Time.new
    date = t.strftime("%Y-%m-%d")

    respond_to do |format|
        @dish.is_today = 1
        @dish.set_date = date
        @dish.save
        format.html { redirect_to dishes_path, notice: @dish.name + ' selected!' }
        format.json { head :no_content }
    end
  end

  def unset_is_today
    @dish = Dish.find(params[:id])

    respond_to do |format|
      @dish.is_today = 0
      @dish.set_date = ''
      @dish.save
      format.html { redirect_to dishes_path, notice: @dish.name + ' unselected!' }
      format.json { head :no_content }
    end
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    date = Time.now
    date_today = date.strftime("%Y-%m-%d")
    @dishes_today = Dish.find_all_by_is_today_and_set_date(true, date_today)

    @last_post = Post.last

    if current_user.account.nil?
      user_account = Account.new(:amount => 0)
      current_user.account = user_account
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admins_only(&block)
    block.call if current_user.try(:admin?)
    nil
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def join_tags(post)
		post.tags.map { |t| t.name }.join(" | ")
	end
end

app/helpers/recharges_helper.rb
module RechargesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dishes/_form.html.erb
<%= form_for @dish , :html =>{:class => 'form-horizontal'} do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <fieldset>
   <div class="control-group">
     <%= f.label :restaurant_id ,:class => 'control-label'%>
     <div class="controls">
       <%= f.select :restaurant_id, Restaurant.all.collect {|c| [ c.name, c.id ] }, :class => 'select'%>
     </div>
   </div>
  <div class="control-group">
    <%= f.label :name ,:class => 'control-label'%>
    <div class="controls">
    <%= f.text_field :name ,:class => 'text_field'%>
      </div>
  </div>
  <div class="field">
    <%= f.label :price , :class => 'control-label' %>
    <div class="controls">
    <%= f.number_field :price ,:class => 'number_field'%>
      </div>
  </div>
  <div class="field">
    <%= f.label :description , :class => 'control-label' %>
    <div class="controls">
    <%= f.text_field :description ,:class => 'text_field' %>
      </div>
  </div>
  <div class="field">
    <%= f.label :remark , :class => 'control-label'  %>
    <div class="controls">
    <%= f.text_field :remark ,:class => 'text_field'%>
      </div>
  </div>
  <div class="form-actions">
    <%= f.submit '确定', :class => 'btn btn-primary'%>
    <%= link_to '取消', dishes_path, :class => 'btn' %>
  </div>
 </fieldset>



<% end %>

app/views/dishes/edit.html.erb
<h1>修改菜品</h1>

<%= render 'form' %>

app/views/dishes/index.html.erb
<h1>菜单</h1>

<table class="table table-striped">
  <tr>
    <th>菜名</th>
    <th>餐馆</th>
    <th>价格</th>
    <th>描述</th>
    <th>今日菜品</th>
    <th>操作</th>
  </tr>

<% @dishes.each do |dish| %>
  <tr>
    <td><%= dish.name %></td>
    <td><%= dish.restaurant.name %></td>
    <td><%= dish.price %></td>
    <td><%= dish.description %></td>
    <td>
      <% if ( dish.is_today && (dish.set_date.today?)) %>
          <%= link_to '取消', unset_is_today_path(dish) ,:class => 'btn btn-xs btn-danger'%>
      <% else %>
          <%= link_to '选定', set_is_today_path(dish), :class => 'btn btn-xs btn-success'%>
      <% end %>
    </td>
    <td><%= link_to '修改', edit_dish_path(dish) ,:class => 'btn btn-xs btn-primary'%>
        <%= link_to '删除', dish, method: :delete, data: { confirm: 'Are you sure?' },:class => 'btn btn-xs btn-danger' %></td>
  </tr>
<% end %>
</table>



<div class="form-actions">
  <%= link_to '新增菜品', new_dish_path, :class => 'btn btn-primary'%>
</div>

app/views/dishes/new.html.erb
<h1>新增菜品</h1>

<%= render 'form' %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dish.name %>
</p>

<p>
  <b>Restaurant:</b>
  <%= @dish.restaurant.name %>
</p>

<p>
  <b>Price:</b>
  <%= @dish.price %>
</p>

<p>
  <b>Description:</b>
  <%= @dish.description %>
</p>

<p>
  <b>Remark:</b>
  <%= @dish.remark %>
</p>


<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>